version: '3'

volumes:
  mysql_data:
      driver: local

services:
  mysql:
      image: mysql:5.7
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      volumes:
        - mysql_data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: keycloak
      networks:
      - micro-network
        
  keycloak:
      image: quay.io/keycloak/keycloak:legacy
      environment:
        DB_VENDOR: MYSQL
        DB_ADDR: mysql
        DB_DATABASE: keycloak
        DB_USER: root
        DB_PASSWORD: root
        KEYCLOAK_USER: root
        KEYCLOAK_PASSWORD: root
      ports:
        - "8080:8080"
      depends_on:
        - mysql
      networks:
      - micro-network
        
networks:
  micro-network:
    driver: bridge